//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStudy.UI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.webxml.felink.com/", ConfigurationName="ServiceReference1.FisrtWebServiceImpl")]
    public interface FisrtWebServiceImpl {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.webxml.felink.com/FisrtWebServiceImpl/getAddressByPhoneNoRequest", ReplyAction="http://ws.webxml.felink.com/FisrtWebServiceImpl/getAddressByPhoneNoResponse")]
        CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponse getAddressByPhoneNo(CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.webxml.felink.com/FisrtWebServiceImpl/getAddressByPhoneNoRequest", ReplyAction="http://ws.webxml.felink.com/FisrtWebServiceImpl/getAddressByPhoneNoResponse")]
        System.Threading.Tasks.Task<CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponse> getAddressByPhoneNoAsync(CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressByPhoneNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAddressByPhoneNo", Namespace="http://ws.webxml.felink.com/", Order=0)]
        public CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequestBody Body;
        
        public getAddressByPhoneNoRequest() {
        }
        
        public getAddressByPhoneNoRequest(CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAddressByPhoneNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getAddressByPhoneNoRequestBody() {
        }
        
        public getAddressByPhoneNoRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressByPhoneNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAddressByPhoneNoResponse", Namespace="http://ws.webxml.felink.com/", Order=0)]
        public CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponseBody Body;
        
        public getAddressByPhoneNoResponse() {
        }
        
        public getAddressByPhoneNoResponse(CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAddressByPhoneNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getAddressByPhoneNoResponseBody() {
        }
        
        public getAddressByPhoneNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FisrtWebServiceImplChannel : CodeStudy.UI.ServiceReference1.FisrtWebServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FisrtWebServiceImplClient : System.ServiceModel.ClientBase<CodeStudy.UI.ServiceReference1.FisrtWebServiceImpl>, CodeStudy.UI.ServiceReference1.FisrtWebServiceImpl {
        
        public FisrtWebServiceImplClient() {
        }
        
        public FisrtWebServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FisrtWebServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FisrtWebServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FisrtWebServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponse CodeStudy.UI.ServiceReference1.FisrtWebServiceImpl.getAddressByPhoneNo(CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest request) {
            return base.Channel.getAddressByPhoneNo(request);
        }
        
        public string getAddressByPhoneNo(string arg0) {
            CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest inValue = new CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest();
            inValue.Body = new CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequestBody();
            inValue.Body.arg0 = arg0;
            CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponse retVal = ((CodeStudy.UI.ServiceReference1.FisrtWebServiceImpl)(this)).getAddressByPhoneNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponse> CodeStudy.UI.ServiceReference1.FisrtWebServiceImpl.getAddressByPhoneNoAsync(CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest request) {
            return base.Channel.getAddressByPhoneNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodeStudy.UI.ServiceReference1.getAddressByPhoneNoResponse> getAddressByPhoneNoAsync(string arg0) {
            CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest inValue = new CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequest();
            inValue.Body = new CodeStudy.UI.ServiceReference1.getAddressByPhoneNoRequestBody();
            inValue.Body.arg0 = arg0;
            return ((CodeStudy.UI.ServiceReference1.FisrtWebServiceImpl)(this)).getAddressByPhoneNoAsync(inValue);
        }
    }
}
